name: agperils-amp
channels:
  - conda-forge
  - defaults
dependencies:
  - python  # cur: 3.10.4
  # - distro  # dep(tabula-py)
  - ipykernel  # jupyter nb
  - ipywidgets  # jupyter nb
  - numpy >= 1.23.3
  - ocrmypdf >= 14.0.3
  - pandas >= 1.5.1
  # - pdfplumber >= 0.7.5
  - pdftotext >= 2.2.2
  - pip
  - poppler >= 22.10.0  # dep(pdf2image), dep(pdftotext)
  - pytesseract >= 0.3.10
  # - requests >= 2.28.1
  # - scikit-learn  # dep(doccano)
  # - setuptools  # dep(spacy)
  # - spacy  # spacy
  # - spacy-transformers  # spacy
  # - wheel  # dep(spacy)
  - pip:
    - black[jupyter] >= 22.10.0
    # - cmake  # dep(python-poppler)
    - dateparser >= 1.1.1  # 1.1.2
    # - doccano
    # - pandera[io] >= 0.13.2
    - pikepdf >= 5.1
    - pdf2image >= 1.16.0  # pdf2image
    # - spacy-lookups-data
    # - tabula-py  # tabula-py
